// Automatically generated by frontend/scripts/sync-games.js. DO NOT EDIT.

import game_21 from "./games/casino-betting/21.json";
import game_31 from "./games/casino-betting/31.json";
import blackjack from "./games/casino-betting/blackjack.json";
import poker from "./games/casino-betting/poker.json";
import authors from "./games/matching-capturing/authors.json";
import casino from "./games/matching-capturing/casino.json";
import dost_kazigi from "./games/matching-capturing/dost-kazigi.json";
import gops from "./games/matching-capturing/gops.json";
import pisti from "./games/matching-capturing/pisti.json";
import scopa from "./games/matching-capturing/scopa.json";
import blof from "./games/party-speed/blof.json";
import clubbers from "./games/party-speed/clubbers.json";
import es_bulmali_speed from "./games/party-speed/es-bulmali-speed.json";
import himbil_esek from "./games/party-speed/himbil-esek.json";
import papaz_kacti from "./games/party-speed/papaz-kacti.json";
import peanuts_nerts from "./games/party-speed/peanuts-nerts.json";
import speed from "./games/party-speed/speed.json";
import spit from "./games/party-speed/spit.json";
import freecell from "./games/patience-strategy/freecell.json";
import kosedeki_papazlar from "./games/patience-strategy/kosedeki-papazlar.json";
import pyramid_solitaire from "./games/patience-strategy/pyramid-solitaire.json";
import solitaire from "./games/patience-strategy/solitaire.json";
import spider_solitaire from "./games/patience-strategy/spider-solitaire.json";
import spite_and_malice from "./games/patience-strategy/spite-and-malice.json";
import game_51 from "./games/rummy-meld-building/51.json";
import carousel_rummy from "./games/rummy-meld-building/carousel-rummy.json";
import gin_rummy from "./games/rummy-meld-building/gin-rummy.json";
import baskan from "./games/shedding/baskan.json";
import crazy_eights_countdown from "./games/shedding/crazy-eights-countdown.json";
import crazy_eights from "./games/shedding/crazy-eights.json";
import pis_yedili from "./games/shedding/pis-yedili.json";
import batak_spades from "./games/trick-taking-trump/batak-spades.json";
import crash from "./games/trick-taking-trump/crash.json";
import cucumber from "./games/trick-taking-trump/cucumber.json";
import esli_batak from "./games/trick-taking-trump/esli-batak.json";
import german_whist from "./games/trick-taking-trump/german-whist.json";
import gommeli_batak from "./games/trick-taking-trump/gommeli-batak.json";
import ikili_batak from "./games/trick-taking-trump/ikili-batak.json";
import minnesota_whist from "./games/trick-taking-trump/minnesota-whist.json";
import pinochle from "./games/trick-taking-trump/pinochle.json";
import sixty_six from "./games/trick-taking-trump/sixty-six.json";

export interface GameData {
  id: string;
  name_tr: string;
  name_en: string;
  originalName: string | null;
  description_tr: string;
  description_en: string;
  rules_tr: string[];
  rules_en: string[];
  minPlayers: number;
  maxPlayers: number;
  deckCount_tr: string;
  deckCount_en: string;
  category_tr: string;
  category_en: string;
  quickRules_tr?: string[] | null;
  quickRules_en?: string[] | null;
  setup_tr?: string[] | null;
  setup_en?: string[] | null;
  objective_tr?: string | null;
  objective_en?: string | null;
  gameplay_tr?: string[] | null;
  gameplay_en?: string[] | null;
  scoring_tr?: string[] | null;
  scoring_en?: string[] | null;
  ending_tr?: string[] | null;
  ending_en?: string[] | null;
  notes_tr?: string[] | null;
  notes_en?: string[] | null;
  customSections?: Array<{
    title_tr: string;
    title_en: string;
    content_tr: string[];
    content_en: string[];
  }> | null;
}

export const GAMES_DATA: GameData[] = [
  (typeof game_21 === "object" ? game_21 : JSON.parse(JSON.stringify(game_21))),
  (typeof game_31 === "object" ? game_31 : JSON.parse(JSON.stringify(game_31))),
  (typeof blackjack === "object" ? blackjack : JSON.parse(JSON.stringify(blackjack))),
  (typeof poker === "object" ? poker : JSON.parse(JSON.stringify(poker))),
  (typeof authors === "object" ? authors : JSON.parse(JSON.stringify(authors))),
  (typeof casino === "object" ? casino : JSON.parse(JSON.stringify(casino))),
  (typeof dost_kazigi === "object" ? dost_kazigi : JSON.parse(JSON.stringify(dost_kazigi))),
  (typeof gops === "object" ? gops : JSON.parse(JSON.stringify(gops))),
  (typeof pisti === "object" ? pisti : JSON.parse(JSON.stringify(pisti))),
  (typeof scopa === "object" ? scopa : JSON.parse(JSON.stringify(scopa))),
  (typeof blof === "object" ? blof : JSON.parse(JSON.stringify(blof))),
  (typeof clubbers === "object" ? clubbers : JSON.parse(JSON.stringify(clubbers))),
  (typeof es_bulmali_speed === "object" ? es_bulmali_speed : JSON.parse(JSON.stringify(es_bulmali_speed))),
  (typeof himbil_esek === "object" ? himbil_esek : JSON.parse(JSON.stringify(himbil_esek))),
  (typeof papaz_kacti === "object" ? papaz_kacti : JSON.parse(JSON.stringify(papaz_kacti))),
  (typeof peanuts_nerts === "object" ? peanuts_nerts : JSON.parse(JSON.stringify(peanuts_nerts))),
  (typeof speed === "object" ? speed : JSON.parse(JSON.stringify(speed))),
  (typeof spit === "object" ? spit : JSON.parse(JSON.stringify(spit))),
  (typeof freecell === "object" ? freecell : JSON.parse(JSON.stringify(freecell))),
  (typeof kosedeki_papazlar === "object" ? kosedeki_papazlar : JSON.parse(JSON.stringify(kosedeki_papazlar))),
  (typeof pyramid_solitaire === "object" ? pyramid_solitaire : JSON.parse(JSON.stringify(pyramid_solitaire))),
  (typeof solitaire === "object" ? solitaire : JSON.parse(JSON.stringify(solitaire))),
  (typeof spider_solitaire === "object" ? spider_solitaire : JSON.parse(JSON.stringify(spider_solitaire))),
  (typeof spite_and_malice === "object" ? spite_and_malice : JSON.parse(JSON.stringify(spite_and_malice))),
  (typeof game_51 === "object" ? game_51 : JSON.parse(JSON.stringify(game_51))),
  (typeof carousel_rummy === "object" ? carousel_rummy : JSON.parse(JSON.stringify(carousel_rummy))),
  (typeof gin_rummy === "object" ? gin_rummy : JSON.parse(JSON.stringify(gin_rummy))),
  (typeof baskan === "object" ? baskan : JSON.parse(JSON.stringify(baskan))),
  (typeof crazy_eights_countdown === "object" ? crazy_eights_countdown : JSON.parse(JSON.stringify(crazy_eights_countdown))),
  (typeof crazy_eights === "object" ? crazy_eights : JSON.parse(JSON.stringify(crazy_eights))),
  (typeof pis_yedili === "object" ? pis_yedili : JSON.parse(JSON.stringify(pis_yedili))),
  (typeof batak_spades === "object" ? batak_spades : JSON.parse(JSON.stringify(batak_spades))),
  (typeof crash === "object" ? crash : JSON.parse(JSON.stringify(crash))),
  (typeof cucumber === "object" ? cucumber : JSON.parse(JSON.stringify(cucumber))),
  (typeof esli_batak === "object" ? esli_batak : JSON.parse(JSON.stringify(esli_batak))),
  (typeof german_whist === "object" ? german_whist : JSON.parse(JSON.stringify(german_whist))),
  (typeof gommeli_batak === "object" ? gommeli_batak : JSON.parse(JSON.stringify(gommeli_batak))),
  (typeof ikili_batak === "object" ? ikili_batak : JSON.parse(JSON.stringify(ikili_batak))),
  (typeof minnesota_whist === "object" ? minnesota_whist : JSON.parse(JSON.stringify(minnesota_whist))),
  (typeof pinochle === "object" ? pinochle : JSON.parse(JSON.stringify(pinochle))),
  (typeof sixty_six === "object" ? sixty_six : JSON.parse(JSON.stringify(sixty_six)))
] as any[];
