const fs = require('fs');
const path = require('path');

const srcGamesDir = path.join(__dirname, '../../backend/iskambil/games');
const destGamesDir = path.join(__dirname, '../app/apps/iskambil/games');
const registryFilePath = path.join(__dirname, '../app/apps/iskambil/games-registry.ts');

// Helper to recursively copy directories
function copyDir(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Clean target directory
if (fs.existsSync(destGamesDir)) {
  fs.rmSync(destGamesDir, { recursive: true, force: true });
}

try {
  // 1. Copy JSON structure
  copyDir(srcGamesDir, destGamesDir);
  console.log(`Successfully copied game JSON folders from backend to frontend/app/apps/iskambil/games`);

  // 2. Scan all copied files to generate static ES module imports registry
  const loadedGames = [];
  const relativeImports = [];

  const scanDir = (dirPath, relativePath = './games') => {
    const files = fs.readdirSync(dirPath);
    for (const file of files) {
      const fullPath = path.join(dirPath, file);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        scanDir(fullPath, `${relativePath}/${file}`);
      } else if (file.endsWith('.json')) {
        const gameId = path.basename(file, '.json');
        let varName = gameId.replace(/[^a-zA-Z0-9]/g, '_');
        if (/^\d/.test(varName)) {
          varName = `game_${varName}`;
        }
        const importPath = `${relativePath}/${file}`;
        relativeImports.push(`import ${varName} from "${importPath}";`);
        loadedGames.push({ varName, id: gameId });
      }
    }
  };

  scanDir(destGamesDir);

  // Generate games-registry.ts code
  const code = `// Automatically generated by frontend/scripts/sync-games.js. DO NOT EDIT.

${relativeImports.join('\n')}

export interface GameData {
  id: string;
  name_tr: string;
  name_en: string;
  originalName: string | null;
  description_tr: string;
  description_en: string;
  rules_tr: string[];
  rules_en: string[];
  minPlayers: number;
  maxPlayers: number;
  deckCount_tr: string;
  deckCount_en: string;
  category_tr: string;
  category_en: string;
  quickRules_tr?: string[] | null;
  quickRules_en?: string[] | null;
  setup_tr?: string[] | null;
  setup_en?: string[] | null;
  objective_tr?: string | null;
  objective_en?: string | null;
  gameplay_tr?: string[] | null;
  gameplay_en?: string[] | null;
  scoring_tr?: string[] | null;
  scoring_en?: string[] | null;
  ending_tr?: string[] | null;
  ending_en?: string[] | null;
  notes_tr?: string[] | null;
  notes_en?: string[] | null;
  customSections?: Array<{
    title_tr: string;
    title_en: string;
    content_tr: string[];
    content_en: string[];
  }> | null;
}

export const GAMES_DATA: GameData[] = [
  ${loadedGames.map(g => `(typeof ${g.varName} === "object" ? ${g.varName} : JSON.parse(JSON.stringify(${g.varName})))`).join(',\n  ')}
] as any[];
`;

  fs.writeFileSync(registryFilePath, code, 'utf-8');
  console.log(`Successfully generated games registry in ${registryFilePath}`);

  // Delete the old single large file to avoid duplication
  const oldDataPath = path.join(__dirname, '../app/apps/iskambil/games-data.ts');
  if (fs.existsSync(oldDataPath)) {
    fs.unlinkSync(oldDataPath);
    console.log(`Removed deprecated games-data.ts`);
  }

} catch (err) {
  console.error("Error copying and syncing games:", err);
  process.exit(1);
}
