/**
 * Smart Recipe Emoji Helper
 * Maps common food keywords to emojis
 */
const EMOJI_MAP: Record<string, string> = {
  patates: "🥔",
  makarna: "🍝",
  spagetti: "🍝",
  tavuk: "🍗",
  et: "🥩",
  köfte: "🧆",
  kofte: "🧆",
  tost: "🥪",
  sandviç: "🥪",
  sandvic: "🥪",
  pilav: "🍚",
  waffle: "🧇",
  vafıl: "🧇",
  cacık: "🥒",
  cacik: "🥒",
  salata: "🥗",
  menemen: "🍳",
  yumurta: "🥚",
  çorba: "🥣",
  corba: "🥣",
  kek: "🍰",
  pasta: "🍰",
  tatlı: "🧁",
  tatli: "🧁",
  pankek: "🥞",
  krep: "🥞",
  akıtma: "🥞",
  akitma: "🥞",
  pizza: "🍕",
  hamburger: "🍔",
  burger: "🍔",
  balık: "🐟",
  balik: "🐟",
  börek: "🥮",
  borek: "🥮",
  kahve: "☕",
  çay: "🍵",
  cay: "🍵",
  meyve: "🍎",
  sebze: "🥦",
  çikolata: "🍫",
  cikolata: "🍫",
  dondurma: "🍦",
  süt: "🥛",
  sut: "🥛",
  peynir: "🧀",
  ekmek: "🍞",
  karnıyarık: "🍆",
  karniyarik: "🍆",
  patlıcan: "🍆",
  patlican: "🍆",
  çilek: "🍓",
  cilek: "🍓",
  muz: "🍌",
  elma: "🍎",
  armut: "🍐",
  biber: "🫑",
  domates: "🍅",
  soğan: "🧅",
  sogan: "🧅",
  sarımsak: "🧄",
  sarimsak: "🧄",
  limon: "🍋",
  portakal: "🍊",
  karpuz: "🍉",
  kavun: "🍈",
  üzüm: "🍇",
  uzum: "🍇",
  havuç: "🥕",
  havuc: "🥕",
  mısır: "🌽",
  misir: "🌽",
  mantar: "🍄",
  avokado: "🥑",
  bal: "🍯",
  çörek: "🍩",
  corek: "🍩",
  kurabiye: "🍪",
  kuru: "🍪",
  su: "💧",
  bira: "🍺",
  şarap: "🍷",
  sarap: "🍷",
  kokteyl: "🍹",
  sosis: "🌭",
  pastırma: "🥓",
  pastirma: "🥓",
};

export function getRecipeEmoji(title: string): string | null {
  const normalized = title.trim().toLowerCase();
  for (const [key, emoji] of Object.entries(EMOJI_MAP)) {
    if (normalized.includes(key)) {
      return emoji;
    }
  }
  return null;
}
