import {
  YoutubeLogo,
  GameController,
  ChefHat,
  Cards,
  Robot,
  ProjectorScreen,
  MaskHappy,
  VideoCamera,
  MapTrifold,
  CreditCard,
  ChartBar,
  IconProps,
  Basket,
  Trophy,
  Sparkle,
  Compass,
  MusicNotes,
  Palette,
  ListChecks,
  Coffee,
  CloudSun,
  FilePdf,
  Timer,
  GraduationCap,
  Users,
  PiggyBank,
  Warning,
  PaperPlaneTilt,
  Buildings,
  Megaphone,
  ChatTeardropDots,
  Storefront,
  Microphone,
  Television,
  Barbell,
  Broom,
  CalendarBlank,
  Leaf,
} from "@phosphor-icons/react";
import React from "react";

export type AppCategory =
  | "Sosyal"
  | "Şehrini Keşfet"
  | "Pratik Araçlar"
  | "Finans & Tasarruf"
  | "Eğlence & Hobi"
  | "Kampüslülere Özel";

export interface MiniApp {
  id: string;
  name: string;
  description: string;
  cta?: string;
  icon: React.ElementType<IconProps>;
  category: AppCategory;
  color: string;
  href: string;
  isImplemented?: boolean;
  subdomain?: string;
  isLocal?: boolean;
  isCancelled?: boolean;
  statusBarColor?: string;
  statusBarStyle?: "light" | "dark";
  navigationBarColor?: string;
  navigationBarStyle?: "light" | "dark";
}

/** Capacitor APK/WebView (build flag veya çalışma anı). */
export { isCapacitorNative, getAppRootUrl, getRootHomeUrl, navigateToAppRoot, APP_HOME_PATH, getPublicSubdomainUrl } from "./app-root";
import { isCapacitorNative } from "./app-root";

/**
 * Generates the correct URL for a mini app, considering subdomains.
 */
export function getAppHref(app: MiniApp): string {
  if (typeof window === "undefined") return app.href;

  // Capacitor / localhost WebView: subdomain yok, iç path kullan.
  if (
    process.env.NEXT_PUBLIC_CAPACITOR === "true" ||
    isCapacitorNative()
  ) {
    return app.href;
  }

  const hostname = window.location.hostname;
  const isLocal =
    hostname === "localhost" ||
    hostname === "127.0.0.1" ||
    hostname.endsWith(".localhost");

  const port = window.location.port;
  const protocol = window.location.protocol;

  if (isLocal) {
    return app.href;
  }

  if (app.subdomain) {
    const rootDomain = process.env.NEXT_PUBLIC_ROOT_DOMAIN ?? "allminiapps.com";
    return `${protocol}//${app.subdomain}.${rootDomain}`;
  }

  const rootDomain = process.env.NEXT_PUBLIC_ROOT_DOMAIN ?? "allminiapps.com";
  return `${protocol}//${rootDomain}${app.href}`;
}

/**
 * Mini app açma — telefonda aynı origin ise router.push, değilse tam URL.
 */
export function navigateToMiniApp(
  app: MiniApp,
  router: { push: (href: string) => void },
): void {
  // Save current location as back target if we are on a business profile page
  if (typeof window !== "undefined") {
    const currentUrl = window.location.href;
    if (currentUrl.includes("/place?slug=") || currentUrl.includes("/place?biz=")) {
      localStorage.setItem("last_business_url", currentUrl);
    } else {
      // Clear it if we are coming from somewhere else
      localStorage.removeItem("last_business_url");
    }
  }

  const href = getAppHref(app);
  if (!href.startsWith("http")) {
    router.push(href);
    return;
  }
  try {
    const url = new URL(href);
    if (typeof window !== "undefined" && url.origin === window.location.origin) {
      router.push(`${url.pathname}${url.search}${url.hash}`);
      return;
    }
  } catch {
    /* external */
  }
  window.location.href = href;
}

const RAW_MINI_APPS: MiniApp[] = [
  {
    id: "kalimba",
    name: "Kalimba",
    description: "Kalimba notalarını interaktif olarak görüntüleyin, dinleyin ve çalın.",
    cta: "Kalimba Çalmaya Başla",
    icon: MusicNotes,
    category: "Eğlence & Hobi",
    color: "#8B5A2B",
    href: "/apps/kalimba",
    isImplemented: true,
    subdomain: "kalimba",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "surdurulebilirlik",
    name: "Sürdürülebiliriz",
    description: "Doğa dostu adımlarını takip et, dünyamıza katkıda bulun.",
    cta: "Doğa Dostu Adımlarını Paylaş",
    icon: Leaf,
    category: "Kampüslülere Özel",
    color: "#059669",
    href: "/apps/surdurulebilirlik",
    isImplemented: true,
    subdomain: "surdurulebilirlik",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "standups",
    name: "Standups",
    description: "Stand-up gösterilerini takip et, bilet al ve özel içerikleri izle.",
    cta: "Stand-up Gösterilerini Takip Et",
    icon: Microphone,
    category: "Eğlence & Hobi",
    color: "#FF9800",
    href: "/apps/standups",
    isImplemented: true,
    subdomain: "standups",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "campus-events",
    name: "Events",
    description: "Şehrindeki tüm etkinlikleri keşfet ve katıl.",
    cta: "Şehirdeki Etkinlikleri Keşfet",
    icon: Megaphone,
    category: "Şehrini Keşfet",
    color: "#00aeef",
    href: "/apps/campus-events",
    isImplemented: true,
    subdomain: "events",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "workplaces",
    name: "Workplaces",
    description: "Çalışmaya uygun kütüphane ve kafeleri keşfet, yenilerini öner.",
    cta: "Çalışacak Mekanları İncele",
    icon: Coffee,
    category: "Şehrini Keşfet",
    color: "#6F4E37",
    href: "/apps/workplaces",
    isImplemented: true,
    subdomain: "workplaces",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAFAFA",
    navigationBarStyle: "light",
  },
  {
    id: "digital-menu",
    name: "Dijital Menü",
    description: "Kafelerin QR menülerini görüntüle, siparişini planla ve masadan garson çağır.",
    cta: "Kafelerin Menülerini İncele",
    icon: ChefHat,
    category: "Şehrini Keşfet",
    color: "#EF4444",
    href: "/apps/digital-menu",
    isImplemented: true,
    subdomain: "menu",
    statusBarColor: "#FDFBF9",
    statusBarStyle: "light",
    navigationBarColor: "#FDFBF9",
    navigationBarStyle: "light",
  },
  {
    id: "stamp-card",
    name: "Müdavim Kartı",
    description: "Anlaşmalı işletmelerden kaşe topla, ücretsiz hediye kazan.",
    cta: "Müdavim Kartlarını Yönet",
    icon: Cards,
    category: "Şehrini Keşfet",
    color: "#F59E0B",
    href: "/apps/stamp-card",
    isImplemented: true,
    subdomain: "stampcard",
    statusBarColor: "#FDFBF7",
    statusBarStyle: "light",
    navigationBarColor: "#FDFBF7",
    navigationBarStyle: "light",
  },

  {
    id: "series-track",
    name: "SeriesTrack",
    description: "İzlediğin dizileri takip et, bölümleri işaretle ve ilerlemeni gör.",
    cta: "İzlediğin Dizileri Takip Et",
    icon: VideoCamera,
    category: "Eğlence & Hobi",
    color: "#E50914",
    href: "/apps/series-track",
    isImplemented: true,
    subdomain: "seriestrack",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "game-companion",
    name: "Yazboz",
    description: "Masa oyunları ve cafe oyunları (101, okey vb.) için dijital skor tahtası, zar ve yardımcı araçlar.",
    cta: "Oyun Skorlarını Tut",
    icon: GameController,
    category: "Eğlence & Hobi",
    color: "#228BE6",
    href: "/apps/game-companion",
    isImplemented: true,
    subdomain: "yazboz",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "iskambil",
    name: "Card Game Codex",
    description: "Klasik kart oyunları için kurallar ve detaylı rehberler.",
    cta: "Kart Oyunlarını Keşfet",
    icon: Cards,
    category: "Eğlence & Hobi",
    color: "#e03131",
    href: "/apps/iskambil",
    isImplemented: true,
    subdomain: "cardgames",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "chocolate-db",
    name: "ChocolateDB",
    description: "Çikolataların IMDB'si! Favori çikolatanı bul, puanla ve yorumla.",
    cta: "Çikolataları Puanla ve Yorumla",
    icon: Basket,
    category: "Eğlence & Hobi",
    color: "#7B3F00",
    href: "/apps/chocolate-db",
    isImplemented: true,
    subdomain: "chocolatedb",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "memedex",
    name: "Memedex",
    description: "Trend meme'ler, doğru kullanım bağlamları ve hazır Giphy template'leri.",
    cta: "Trend Meme'leri Keşfet",
    icon: MaskHappy,
    category: "Eğlence & Hobi",
    color: "#d946ef",
    href: "/apps/memedex",
    isImplemented: true,
    subdomain: "memedex",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "icon-set-guide",
    name: "Icon Set Guide",
    description: "Compare open-source icon sets in real UI previews",
    cta: "İkon Setlerini Karşılaştır",
    icon: Palette,
    category: "Pratik Araçlar",
    color: "#4C6EF5",
    href: "/apps/icon-set-guide",
    isImplemented: true,
    subdomain: "iconguide",
    isCancelled: true,
  },
  {
    id: "subcenter",
    name: "Subcenter",
    description: "Tüm aboneliklerini ve harcamalarını takip et.",
    cta: "Aboneliklerini Tek Yerden Yönet",
    icon: CreditCard,
    category: "Finans & Tasarruf",
    color: "#339AF0",
    href: "/apps/subcenter",
    isImplemented: true,
    subdomain: "subcenter",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "daily-weather",
    name: "Daily Weather",
    description: "Her sabah İstanbul hava durumu bildirimi al.",
    cta: "Günlük Hava Durumunu Al",
    icon: CloudSun,
    category: "Pratik Araçlar",
    color: "#38BDF8",
    href: "/apps/daily-weather",
    isImplemented: true,
    subdomain: "weather",
    isCancelled: true,
    statusBarColor: "#F0E6FF",
    statusBarStyle: "light",
    navigationBarColor: "#FFF9E6",
    navigationBarStyle: "light",
  },
  {
    id: "suggest",
    name: "Suggest",
    description: "Arkadaşlarına film, dizi, oyun veya mekan tavsiye et.",
    cta: "Arkadaşlarına Önerilerde Bulun",
    icon: PaperPlaneTilt,
    category: "Sosyal",
    color: "#6366f1",
    href: "/apps/suggest",
    isImplemented: true,
    subdomain: "suggest",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "pdf-tools",
    name: "Pdf Tools",
    description: "PDF sayfalarını düzenle, yeniden sırala ve sil. Tamamen cihazında çalışır.",
    cta: "PDF Dosyalarını Düzenle",
    icon: FilePdf,
    category: "Pratik Araçlar",
    color: "#E03131",
    href: "/apps/pdf-tools",
    isImplemented: true,
    subdomain: "pdf",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "catan-bot",
    name: "Catan Bot",
    description: "Helper for Catan board game",
    cta: "Catan Yardımcısını Kullan",
    icon: Robot,
    category: "Eğlence & Hobi",
    color: "#845EF7",
    href: "/apps/catan-bot",
    isImplemented: true,
    subdomain: "catan",
    isCancelled: true,
  },
  {
    id: "tournament-manager",
    name: "Turnuva Merkezi",
    description: "Lig ve Eleme usulü turnuvalar oluştur ve yönet",
    cta: "Turnuvalar Oluştur ve Yönet",
    icon: Trophy,
    category: "Eğlence & Hobi",
    color: "#FCC419",
    href: "/apps/tournament-editor",
    isImplemented: true,
    subdomain: "tournaments",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "youtube-series",
    name: "Youtube Discover",
    description: "Yeni seriler keşfet ve izleme listeni yönet",
    cta: "Yeni Seriler Keşfet",
    icon: YoutubeLogo,
    category: "Eğlence & Hobi",
    color: "#FF0000",
    href: "/apps/youtube-discover",
    isImplemented: true,
    subdomain: "ytdb",
    isCancelled: true,
  },
  {
    id: "film-graph",
    name: "Film Graph",
    description: "Explore connections between movies",
    cta: "Film Bağlantılarını Keşfet",
    icon: ProjectorScreen,
    category: "Eğlence & Hobi",
    color: "#ef4444",
    href: "/apps/film-graph",
    isImplemented: true,
    subdomain: "filmgraph",
    isCancelled: true,
  },
  {
    id: "movies-this-year",
    name: "Movies This Year",
    description: "Bu yılın en popüler ve beklenen filmlerini keşfet",
    cta: "Yılın Popüler Filmlerini Gör",
    icon: VideoCamera,
    category: "Eğlence & Hobi",
    color: "#E50914",
    href: "/apps/movies-this-year",
    isImplemented: true,
    subdomain: "movies",
    isCancelled: true,
  },
  {
    id: "meme-sorts",
    name: "Meme Sorts",
    description: "BogoSort, StalinSort, ThanosSort...",
    cta: "Meme Algoritmalarını İncele",
    icon: ChartBar,
    category: "Eğlence & Hobi",
    color: "#748FFC",
    href: "/apps/meme-sorts",
    isImplemented: true,
    isCancelled: true,
  },
  {
    id: "itu-yemekhane",
    name: "Campus Meals",
    description: "Günün menüsünü takip et ve bildirim al.",
    cta: "Kampüs Menüsünü Takip Et",
    icon: ChefHat,
    category: "Kampüslülere Özel",
    color: "#001A33",
    href: "/apps/itu-yemekhane",
    isImplemented: true,
    subdomain: "itumeals",
    isLocal: true,
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#F0F2F5",
    navigationBarStyle: "light",
  },
  {
    id: "sticker-editor",
    name: "Sticker Maker",
    description: "WhatsApp için kendi sticker paketlerini tasarla",
    cta: "Kendi Sticker'larını Tasarla",
    icon: MaskHappy,
    category: "Pratik Araçlar",
    color: "#25D366",
    href: "/apps/sticker-editor",
    isImplemented: true,
    subdomain: "sticker",
    isCancelled: true,
  },
  {
    id: "kim-gelir",
    name: "Ne Yapsak?",
    description: "Hızlıca aktivite daveti veya anket oluştur, arkadaşlarını davet et.",
    cta: "Etkinlik Daveti Oluştur",
    icon: Users,
    category: "Sosyal",
    color: "#FF5252",
    href: "/apps/kim-gelir",
    isImplemented: true,
    subdomain: "kimgelir",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "eksik-var",
    name: "Eksik Var",
    description: "Alışveriş listenizi ve evinizin eksiklerini kolayca yönetin.",
    cta: "Alışveriş Listem",
    icon: ListChecks,
    category: "Kampüslülere Özel",
    color: "#10B981",
    href: "/apps/eksik-var",
    isImplemented: true,
    subdomain: "eksikvar",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#ffffff",
    navigationBarStyle: "light",
  },
  {
    id: "map-tracker",
    name: "Harita Takip",
    description: "Google Maps listelerini import et ve gitme durumunu takip et",
    cta: "Harita Listelerini Takip Et",
    icon: MapTrifold,
    category: "Şehrini Keşfet",
    color: "#4dabf7",
    href: "/apps/map-tracker",
    isImplemented: true,
    subdomain: "maptracker",
    isCancelled: true,
  },
  {
    id: "meal-planner",
    name: "Meal Planner",
    description: "Tariflerini kaydet, haftalık yemek planını oluştur.",
    cta: "Haftalık Yemeklerini Planla",
    icon: ChefHat,
    category: "Kampüslülere Özel",
    color: "#F97316",
    href: "/apps/recipe",
    isImplemented: true,
    subdomain: "recipe",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "gym",
    name: "Gym",
    description: "Antrenmanlarını kaydet, rutinler oluştur ve ilerlemeni takip et.",
    cta: "Spor Antrenmanlarım",
    icon: Barbell,
    category: "Kampüslülere Özel",
    color: "#8B5CF6",
    href: "/apps/gym",
    isImplemented: true,
    subdomain: "gym",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "ev-isleri",
    name: "Ev İşleri",
    description: "Haftalık ev işi board'u oluştur, görevleri kişilere ata ve tamamla.",
    cta: "Ev İşlerini Planla",
    icon: Broom,
    category: "Kampüslülere Özel",
    color: "#14B8A6",
    href: "/apps/ev-isleri",
    isImplemented: true,
    subdomain: "evisleri",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "rutinler",
    name: "Ajanda",
    description: "Günlük rutinlerini takip et ve yapılacak işlerini yönet.",
    cta: "Ajandanı Yönet",
    icon: CalendarBlank,
    category: "Kampüslülere Özel",
    color: "#7C3AED",
    href: "/apps/rutinler",
    isImplemented: true,
    subdomain: "rutinler",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "ne-yapsam",
    name: "Ne Yapsak?",
    description: "Bugün ne yapsam? Tek başına yapabileceğin aktiviteleri keşfet.",
    cta: "Bugün Ne Yapsak?",
    icon: Sparkle,
    category: "Sosyal",
    color: "#FA5252",
    href: "/apps/stop-scroll",
    isImplemented: true,
    subdomain: "neyapsam",
    isCancelled: true,
  },
  {
    id: "hobby-center",
    name: "Hobby Center",
    description: "Yeni hobiler keşfet, yol haritalarını takip et ve kaynaklara eriş.",
    cta: "Yeni Hobiler Keşfet",
    icon: Compass,
    category: "Eğlence & Hobi",
    color: "#D4AF37",
    href: "/apps/hobby-center",
    isImplemented: true,
    subdomain: "hobby",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "concert-list",
    name: "My Concert List",
    description: "Gittiğin konserleri tarihleri ve notlarınla takip et.",
    cta: "Gittiğin Konserleri Listele",
    icon: MusicNotes,
    category: "Eğlence & Hobi",
    color: "#FF1493",
    href: "/apps/concert-list",
    isImplemented: true,
    subdomain: "concerts",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "campus-concerts",
    name: "Campus Concerts",
    description: "Kampüsün Geçmiş Konserleri",
    cta: "Kampüs Konserlerini Takip Et",
    icon: MusicNotes,
    category: "Kampüslülere Özel",
    color: "#845EF7",
    href: "/apps/campus-concerts",
    isImplemented: true,
    subdomain: "kampus",
    isCancelled: true,
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#F8FAFC",
    navigationBarStyle: "light",
  },
  {
    id: "one-day-city-guide",
    name: "One Day City Guide",
    description: "Seçtiğin şehirde bir günde ne yapılır? En iyi rotalar ve tavsiyeler.",
    cta: "Şehir Rotalarını İncele",
    icon: Compass,
    category: "Şehrini Keşfet",
    color: "#0F766E",
    href: "/apps/one-day-city-guide",
    isImplemented: true,
    subdomain: "oneday",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#F8FAFC",
    navigationBarStyle: "light",
  },
  {
    id: "tasket",
    name: "Tasket",
    description: "Notlarını ve görevlerini sepetinde topla, listelerle organize et",
    cta: "Görevlerini ve Notlarını Yönet",
    icon: ListChecks,
    category: "Pratik Araçlar",
    color: "#20c997",
    href: "/apps/tasket",
    isImplemented: true,
    subdomain: "tasket",
    isCancelled: true,
  },
  {
    id: "pomodoro",
    name: "Melt & Work",
    description: "Buz erimesi animasyonlu odaklanma sayacı",
    cta: "Odaklanma Sayacını Başlat",
    icon: Timer,
    category: "Pratik Araçlar",
    color: "#4dabf7",
    href: "/apps/pomodoro",
    isImplemented: true,
    isLocal: true,
    subdomain: "melt",
    isCancelled: true,
  },
  {
    id: "birikim",
    name: "Birikim",
    description: "Birikim hedefleri koy, hesaplarını yönet ve tasarruflarını takip et!",
    cta: "Birikim Hedeflerini Takip Et",
    icon: PiggyBank,
    category: "Finans & Tasarruf",
    color: "#6366F1",
    href: "/apps/birikim",
    isImplemented: true,
    subdomain: "birikim",
    isCancelled: true,
  },
  {
    id: "tasarruf-challenges",
    name: "Tasarruf",
    description: "Tasarruf önerilerini takip et, harcamalarını azalt ve hedeflerine ulaş.",
    cta: "Tasarruf Önerilerini İncele",
    icon: PiggyBank,
    category: "Finans & Tasarruf",
    color: "#40C057",
    href: "/apps/tasarruf-challenges",
    isImplemented: true,
    subdomain: "tasarruf",
    isCancelled: true,
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "penalty-jar",
    name: "Penalty Jar",
    description: "Arkadaşlarınla belirlediğin kuralları kimlerin çiğnediğini ve ceza kavanozunu takip et!",
    cta: "Ceza Kavanozunu Takip Et",
    icon: Warning,
    category: "Eğlence & Hobi",
    color: "#E03131",
    href: "/apps/penalty-jar",
    isImplemented: true,
    subdomain: "kavanoz",
    isCancelled: true,
  },
  {
    id: "budget",
    name: "Budget",
    description: "Bireysel ve ortak bütçe takibi, arkadaşlarınla kolay borç bölüşümü.",
    cta: "Bütçeni ve Borçlarını Yönet",
    icon: CreditCard,
    category: "Finans & Tasarruf",
    color: "#EC4899",
    href: "/apps/budget",
    isImplemented: true,
    subdomain: "budget",
    isCancelled: true,
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "esles",
    name: "Eşleş",
    description: "Online oyun arkadaşı bul! İlan oluştur, oyuncu ara ve hemen takıma katıl.",
    cta: "Oyun Arkadaşı Bul",
    icon: GameController,
    category: "Eğlence & Hobi",
    color: "#7C3AED",
    href: "/apps/esles",
    isImplemented: true,
    subdomain: "esles",
    isCancelled: true,
  },
  {
    id: "gaming-hub",
    name: "Gaming Hub",
    description: "Oynayacak oyun bul, arkadaşlarınla keşfet, fiyat takibi yap ve sağlıklı oyun alışkanlıkları oluştur.",
    cta: "Gaming Hub'ı Aç",
    icon: GameController,
    category: "Eğlence & Hobi",
    color: "#7C3AED",
    href: "/apps/gaming-hub",
    isImplemented: true,
    subdomain: "gaminghub",
    statusBarColor: "#FAF9F7",
    statusBarStyle: "light",
    navigationBarColor: "#FAF9F7",
    navigationBarStyle: "light",
  },
  {
    id: "apply-tracker",
    name: "Başvuru Takip",
    description: "İş başvurularını, ilan linklerini ve süreç durumlarını takip et.",
    cta: "İş Başvurularını Takip Et",
    icon: Buildings,
    category: "Pratik Araçlar",
    color: "#6366f1",
    href: "/apps/apply-tracker",
    isImplemented: true,
    subdomain: "basvuru",
    isCancelled: true,
  },
];

const RAW_BUSINESS_APPS: MiniApp[] = [
  {
    id: "business-page",
    name: "İşletme Sayfası",
    description: "İşletmenizin dijital kimliğini ve Linktree tarzı profilini yönetin.",
    cta: "İşletme Profilini Yönet",
    icon: Storefront,
    category: "Şehrini Keşfet",
    color: "#10B981",
    href: "/apps/business-page",
    isImplemented: true,
    subdomain: "page",
  },
  {
    id: "digital-menu",
    name: "Dijital Menü",
    description: "Ürünlerinizi listeleyin, fiyatları güncelleyin ve QR menünüzü yönetin.",
    cta: "Dijital Menünü Oluştur",
    icon: ChefHat,
    category: "Şehrini Keşfet",
    color: "#EF4444",
    href: "/apps/digital-menu",
    isImplemented: true,
    subdomain: "menu",
    statusBarColor: "#FDFBF9",
    statusBarStyle: "light",
    navigationBarColor: "#FDFBF9",
    navigationBarStyle: "light",
  },
  {
    id: "campus-events",
    name: "Events",
    description: "İşletmenize ait etkinlikleri oluşturun, paylaşın ve katılımcıları yönetin.",
    cta: "İşletme Etkinliklerini Yönet",
    icon: Megaphone,
    category: "Şehrini Keşfet",
    color: "#00aeef",
    href: "/apps/campus-events",
    isImplemented: true,
    subdomain: "events",
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#F8FAFC",
    navigationBarStyle: "light",
  },
  {
    id: "stamp-card",
    name: "Müdavim Kartı",
    description: "Müdavim programınızı yönetin, müşterilerinize dijital kaşe verin.",
    cta: "Müdavim Programını Yönet",
    icon: Cards,
    category: "Şehrini Keşfet",
    color: "#F59E0B",
    href: "/apps/stamp-card",
    isImplemented: true,
    subdomain: "stampcard",
    statusBarColor: "#FDFBF7",
    statusBarStyle: "light",
    navigationBarColor: "#FDFBF7",
    navigationBarStyle: "light",
  },
  {
    id: "workplaces",
    name: "Workplaces",
    description: "İşletme bilgilerinizi, çalışma saatlerinizi ve olanaklarınızı güncelleyin.",
    cta: "İşletme Bilgilerini Güncelle",
    icon: Coffee,
    category: "Şehrini Keşfet",
    color: "#6F4E37",
    href: "/apps/workplaces",
    isImplemented: true,
    subdomain: "workplaces",
    isCancelled: true,
    statusBarColor: "#ffffff",
    statusBarStyle: "light",
    navigationBarColor: "#FAFAFA",
    navigationBarStyle: "light",
  },
  {
    id: "board-game-clubs",
    name: "Board Game Clubs",
    description: "Oyun kütüphanenizi yönetin ve kulüp üyeleriyle etkileşime geçin.",
    cta: "Kutu Oyunlarımızı Keşfedin",
    icon: GameController,
    category: "Eğlence & Hobi",
    color: "#D4A830",
    href: "/apps/board-game-clubs",
    isImplemented: true,
    subdomain: "bgc",
  },
  {
    id: "feedback-board",
    name: "Feedback Board",
    description: "Müşterilerinizden gelen geri bildirimleri tek bir yerden takip edin.",
    cta: "Müşteri Geri Bildirimlerini Takip Et",
    icon: ChatTeardropDots,
    category: "Pratik Araçlar",
    color: "#7c3aed",
    href: "/apps/feedback-board",
    isImplemented: true,
    subdomain: "feedback",
  },
  {
    id: "tutor-crm",
    name: "Tutor Place",
    description: "Öğrenci kayıtlarını, ders programlarını ve ödemeleri organize edin.",
    cta: "Öğrenci ve Ders Programını Yönet",
    icon: GraduationCap,
    category: "Pratik Araçlar",
    color: "#228BE6",
    href: "/apps/tutor-crm",
    isImplemented: true,
    subdomain: "tutorplace",
  },
  {
    id: "standups",
    name: "Standups",
    description: "Komedyenleri ve gösterileri yönetin, içerik ekleyin.",
    cta: "Komedyen ve Gösterileri Yönet",
    icon: Microphone,
    category: "Eğlence & Hobi",
    color: "#FF9800",
    href: "/apps/standups",
    isImplemented: true,
    subdomain: "standups",
  },
];

export const BUSINESS_APPS: MiniApp[] = RAW_BUSINESS_APPS;

export const MINI_APPS: MiniApp[] = RAW_MINI_APPS;
