// Code generated by the Encore v1.56.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-mini-apps-center-8u7i.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the mini-apps-center-8u7i Encore application.
 */
export default class Client {
    public readonly itu_yemekhane: itu_yemekhane.ServiceClient
    public readonly kiler: kiler.ServiceClient
    public readonly recipe: recipe.ServiceClient
    public readonly scrape: scrape.ServiceClient
    public readonly subcenter: subcenter.ServiceClient
    public readonly tournament: tournament.ServiceClient
    public readonly users: users.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.itu_yemekhane = new itu_yemekhane.ServiceClient(base)
        this.kiler = new kiler.ServiceClient(base)
        this.recipe = new recipe.ServiceClient(base)
        this.scrape = new scrape.ServiceClient(base)
        this.subcenter = new subcenter.ServiceClient(base)
        this.tournament = new tournament.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * ITU Yemekhane scraper service
 */
export namespace itu_yemekhane {
    export interface Dish {
        id: string
        name: string
        category: string
        calories: number
    }

    export interface MenuResponse {
        date: string
        mealType: string
        dishes: Dish[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDislikedDishes = this.getDislikedDishes.bind(this)
            this.getMenu = this.getMenu.bind(this)
            this.toggleDislike = this.toggleDislike.bind(this)
        }

        /**
         * Get all disliked dishes for global display at the bottom via Supabase RPC.
         * GET /disliked
         */
        public async getDislikedDishes(): Promise<{
    dishes: string[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/disliked`)
            return await resp.json() as {
    dishes: string[]
}
        }

        /**
         * Scrapes the ITU cafeteria menu from the provided external page.
         */
        public async getMenu(): Promise<MenuResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/menu`)
            return await resp.json() as MenuResponse
        }

        /**
         * Toggles a dish (name) in the disliked library using Supabase RPC.
         * POST /disliked
         */
        public async toggleDislike(params: {
    dishName: string
}): Promise<{
    status: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/disliked`, JSON.stringify(params))
            return await resp.json() as {
    status: string
}
        }
    }
}

export namespace kiler {
    export interface AddItemRequest {
        userId: string
        name: string
        amount: number
        unit: string
        storageType: StorageType
        purchaseDate: string
        expiryDate?: string
    }

    export interface AddItemResponse {
        item: PantryItem | null
    }

    export interface DeleteItemRequest {
        userId: string
    }

    export interface DeleteItemResponse {
        success: boolean
    }

    export interface GetItemsResponse {
        items: PantryItem[]
    }

    export interface PantryItem {
        id: string
        "user_id": string
        name: string
        amount: number
        unit: string
        "storage_type": StorageType
        "purchase_date": string
        "expiry_date"?: string
        "created_at": string
    }

    export type StorageType = "fridge" | "freezer" | "pantry"

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addItem = this.addItem.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.getItems = this.getItems.bind(this)
        }

        /**
         * Kilere yeni ürün ekler
         * POST /kiler/add
         */
        public async addItem(params: AddItemRequest): Promise<AddItemResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/kiler/add`, JSON.stringify(params))
            return await resp.json() as AddItemResponse
        }

        /**
         * Kilerinden ürün siler
         * DELETE /kiler/item/:id
         */
        public async deleteItem(id: string, params: DeleteItemRequest): Promise<DeleteItemResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/kiler/item/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as DeleteItemResponse
        }

        /**
         * Kullanıcının kilerindeki tüm ürünleri getirir
         * GET /kiler/items/:userId
         */
        public async getItems(userId: string): Promise<GetItemsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/kiler/items/${encodeURIComponent(userId)}`)
            return await resp.json() as GetItemsResponse
        }
    }
}

/**
 * Recipe service - handles all recipe CRUD operations
 */
export namespace recipe {
    export interface CreateRecipeRequest {
        title: string
        userId: string
        ingredients?: lib.Ingredient[] | null
        instructions?: lib.Instruction[] | null
    }

    export interface CreateRecipeResponse {
        recipe: lib.Recipe | null
    }

    export interface DeleteRecipeRequest {
        userId: string
    }

    export interface DeleteRecipeResponse {
        success: boolean
    }

    export interface GetRecipeByIdResponse {
        recipe: lib.Recipe | null
    }

    export interface GetUserRecipesResponse {
        recipes: lib.RecipeSummary[]
    }

    export interface UpdateRecipeRequest {
        userId: string
        title: string
        ingredients: lib.Ingredient[] | null
        instructions: lib.Instruction[] | null
    }

    export interface UpdateRecipeResponse {
        recipe: lib.Recipe | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createRecipe = this.createRecipe.bind(this)
            this.deleteRecipe = this.deleteRecipe.bind(this)
            this.getRecipeById = this.getRecipeById.bind(this)
            this.getUserRecipes = this.getUserRecipes.bind(this)
            this.updateRecipe = this.updateRecipe.bind(this)
        }

        /**
         * Yeni tarif oluşturur (kullanıcı ID'si, malzemeler ve yapılış ile)
         * POST /recipe/create
         */
        public async createRecipe(params: CreateRecipeRequest): Promise<CreateRecipeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/recipe/create`, JSON.stringify(params))
            return await resp.json() as CreateRecipeResponse
        }

        /**
         * Tarif siler (sadece tarifi oluşturan kullanıcı silebilir)
         * DELETE /recipe/:recipeId
         */
        public async deleteRecipe(recipeId: string, params: DeleteRecipeRequest): Promise<DeleteRecipeResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/recipe/${encodeURIComponent(recipeId)}`, undefined, {query})
            return await resp.json() as DeleteRecipeResponse
        }

        /**
         * Tek bir tarifin tüm detaylarını getirir (recipe ID ile)
         * GET /recipe/:recipeId
         */
        public async getRecipeById(recipeId: string): Promise<GetRecipeByIdResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/recipe/${encodeURIComponent(recipeId)}`)
            return await resp.json() as GetRecipeByIdResponse
        }

        /**
         * Belirli kullanıcının tariflerini getirir (RPC fonksiyonu kullanarak)
         * GET /recipe/user/:userId
         */
        public async getUserRecipes(userId: string): Promise<GetUserRecipesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/recipe/user/${encodeURIComponent(userId)}`)
            return await resp.json() as GetUserRecipesResponse
        }

        /**
         * Tarifi günceller (sadece tarifi oluşturan kullanıcı güncelleyebilir)
         * PUT /recipe/:recipeId
         */
        public async updateRecipe(recipeId: string, params: UpdateRecipeRequest): Promise<UpdateRecipeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/recipe/${encodeURIComponent(recipeId)}`, JSON.stringify(params))
            return await resp.json() as UpdateRecipeResponse
        }
    }
}

/**
 * Scrape service - handles web scraping operations (Instagram, etc.)
 */
export namespace scrape {
    export interface ScrapeReelsRequest {
        url: string
    }

    export interface ScrapeReelsResponse {
        success: boolean
        caption?: string
        error?: string
        username?: string
        thumbnail?: string
    }

    export interface ScrapeYouTubeShortRequest {
        url: string
    }

    export interface ScrapeYouTubeShortResponse {
        success: boolean
        title?: string
        description?: string
        error?: string
        author?: string
        thumbnail?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.scrapeInstagramReel = this.scrapeInstagramReel.bind(this)
            this.scrapeYouTubeShort = this.scrapeYouTubeShort.bind(this)
        }

        /**
         * Scrapes Instagram Reels caption using Puppeteer
         * No authentication required - uses browser automation
         */
        public async scrapeInstagramReel(params: ScrapeReelsRequest): Promise<ScrapeReelsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/scrape/instagram/reels`, JSON.stringify(params))
            return await resp.json() as ScrapeReelsResponse
        }

        /**
         * Scrapes YouTube Shorts using oEmbed API
         * No authentication required
         */
        public async scrapeYouTubeShort(params: ScrapeYouTubeShortRequest): Promise<ScrapeYouTubeShortResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/scrape/youtube/shorts`, JSON.stringify(params))
            return await resp.json() as ScrapeYouTubeShortResponse
        }
    }
}

/**
 * Subscription Center service - handles subscription tracking
 */
export namespace subcenter {
    export interface CreateSubscriptionRequest {
        userId: string
        name: string
        planName?: string
        region?: string
        price: number
        currency: string
        cycle: string
        category: string
        color: string
        icon: string
        startDate: string
    }

    export interface CreateSubscriptionResponse {
        subscription: Subscription | null
    }

    export interface DeleteSubscriptionRequest {
        userId: string
    }

    export interface DeleteSubscriptionResponse {
        success: boolean
    }

    export interface GetGlobalPresetsResponse {
        presets: GlobalPreset[]
    }

    export interface GetUserSubscriptionsResponse {
        subscriptions: Subscription[]
    }

    export interface GlobalPreset {
        id: string
        name: string
        "plan_name": string
        region: string
        "avg_price": number
        currency: string
        category: string
        color: string
        icon: string
        "usage_count": number
    }

    export interface Subscription {
        id: string
        "user_id": string
        name: string
        "plan_name": string
        region: string
        price: number
        currency: string
        cycle: string
        category: string
        color: string
        icon: string
        "start_date": string
        "created_at": string
    }

    export interface UpdateSubscriptionRequest {
        userId: string
        name: string
        planName: string
        region: string
        price: number
        currency: string
        cycle: string
        category: string
        color: string
        icon: string
        startDate: string
    }

    export interface UpdateSubscriptionResponse {
        subscription: Subscription | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createSubscription = this.createSubscription.bind(this)
            this.deleteSubscription = this.deleteSubscription.bind(this)
            this.getGlobalPresets = this.getGlobalPresets.bind(this)
            this.getUserSubscriptions = this.getUserSubscriptions.bind(this)
            this.updateSubscription = this.updateSubscription.bind(this)
        }

        /**
         * Create a new subscription and update community presets
         * POST /subcenter/create
         */
        public async createSubscription(params: CreateSubscriptionRequest): Promise<CreateSubscriptionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/subcenter/create`, JSON.stringify(params))
            return await resp.json() as CreateSubscriptionResponse
        }

        /**
         * Delete a subscription
         * DELETE /subcenter/:id
         */
        public async deleteSubscription(id: string, params: DeleteSubscriptionRequest): Promise<DeleteSubscriptionResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/subcenter/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as DeleteSubscriptionResponse
        }

        /**
         * Get top community-driven subscription presets
         * GET /subcenter/presets
         */
        public async getGlobalPresets(): Promise<GetGlobalPresetsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/subcenter/presets`)
            return await resp.json() as GetGlobalPresetsResponse
        }

        /**
         * Get all subscriptions for a user
         * GET /subcenter/user/:userId
         */
        public async getUserSubscriptions(userId: string): Promise<GetUserSubscriptionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/subcenter/user/${encodeURIComponent(userId)}`)
            return await resp.json() as GetUserSubscriptionsResponse
        }

        /**
         * Update a subscription
         * PUT /subcenter/:id
         */
        public async updateSubscription(id: string, params: UpdateSubscriptionRequest): Promise<UpdateSubscriptionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/subcenter/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UpdateSubscriptionResponse
        }
    }
}

export namespace tournament {
    export interface Match {
        id: string
        "tournament_id": string
        phase: "league" | "bracket"
        round: number
        "player1_id": string | null
        "player2_id": string | null
        "winner_id": string | null
        score1: number
        score2: number
        status: "upcoming" | "playing" | "finished" | "abandoned"
        username1?: string
        username2?: string
        avatar1?: string
        avatar2?: string
    }

    export interface MatchesResponse {
        matches: Match[]
    }

    export interface Participant {
        id: string
        "tournament_id": string
        "user_id": string
        username: string
        avatar?: string
        points: number
        wins: number
        losses: number
        average: number
    }

    export interface StandingsResponse {
        participants: Participant[]
    }

    export interface Tournament {
        id: string
        name: string
        slug: string
        icon?: string
        status: "upcoming" | "active" | "completed"
        "admin_user_id": string
        capacity: number
        "advance_count": number
        "current_league_round": number
        "league_match_count": number
        format: "league_knockout" | "knockout"
        "start_at"?: string
        "winner_id"?: string
        "participants_count"?: number
        "is_joined"?: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.advanceToBracket = this.advanceToBracket.bind(this)
            this.getStandings = this.getStandings.bind(this)
            this.getTournamentDetails = this.getTournamentDetails.bind(this)
            this.getTournamentMatches = this.getTournamentMatches.bind(this)
            this.joinTournament = this.joinTournament.bind(this)
            this.startTournament = this.startTournament.bind(this)
            this.updateMatchScore = this.updateMatchScore.bind(this)
        }

        /**
         * Lig aşamasını bitirir ve Bracket (Eleme) aşamasını başlatır
         */
        public async advanceToBracket(slug: string, params: {
    adminUserId: string
}): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/tournament/${encodeURIComponent(slug)}/advance-to-bracket`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Puan durumunu getirir
         */
        public async getStandings(slug: string): Promise<StandingsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/tournament/${encodeURIComponent(slug)}/standings`)
            return await resp.json() as StandingsResponse
        }

        /**
         * Turnuva detaylarını getirir
         */
        public async getTournamentDetails(slug: string, params: {
    userId?: string
}): Promise<Tournament> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/tournament/${encodeURIComponent(slug)}`, undefined, {query})
            return await resp.json() as Tournament
        }

        /**
         * Maçları getirir
         */
        public async getTournamentMatches(slug: string): Promise<MatchesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/tournament/${encodeURIComponent(slug)}/matches`)
            return await resp.json() as MatchesResponse
        }

        /**
         * Turnuvaya katılır
         */
        public async joinTournament(slug: string, params: {
    userId: string
    username: string
    avatar?: string
}): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/tournament/${encodeURIComponent(slug)}/join`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Turnuvayı başlatır ve ilk tur maçlarını oluşturur
         */
        public async startTournament(slug: string, params: {
    adminUserId: string
}): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/tournament/${encodeURIComponent(slug)}/start`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Maç skorunu günceller
         */
        public async updateMatchScore(matchId: string, params: {
    score1: number
    score2: number
    adminUserId: string
}): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/tournament/match/${encodeURIComponent(matchId)}/score`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }
    }
}

/**
 * Users service - handles user identity and mapping with Clerk ID
 */
export namespace users {
    export interface CreateUserRequest {
        clerkId: string
    }

    export interface CreateUserResponse {
        user: lib.User | null
    }

    export interface GetOrCreateUserRequest {
        clerkId: string
    }

    export interface GetOrCreateUserResponse {
        user: lib.User | null
        isNewUser: boolean
    }

    export interface GetUserByClerkIdResponse {
        user: lib.User | null
    }

    export interface SaveFcmTokenRequest {
        clerkId: string
        token: string
        deviceType: string
    }

    export interface SaveFcmTokenResponse {
        success: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createUser = this.createUser.bind(this)
            this.getOrCreateUser = this.getOrCreateUser.bind(this)
            this.getUserByClerkId = this.getUserByClerkId.bind(this)
            this.saveFcmToken = this.saveFcmToken.bind(this)
        }

        /**
         * Clerk ID ile yeni Supabase user oluşturur
         * POST /identity/user/create
         */
        public async createUser(params: CreateUserRequest): Promise<CreateUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/users/user/create`, JSON.stringify(params))
            return await resp.json() as CreateUserResponse
        }

        /**
         * Clerk ID ile Supabase user'ı getirir, yoksa oluşturur
         * POST /identity/user/get-or-create
         */
        public async getOrCreateUser(params: GetOrCreateUserRequest): Promise<GetOrCreateUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/users/user/get-or-create`, JSON.stringify(params))
            return await resp.json() as GetOrCreateUserResponse
        }

        /**
         * Clerk ID ile Supabase user'ı getirir
         * GET /identity/user/clerk/:clerkId
         */
        public async getUserByClerkId(clerkId: string): Promise<GetUserByClerkIdResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/user/clerk/${encodeURIComponent(clerkId)}`)
            return await resp.json() as GetUserByClerkIdResponse
        }

        /**
         * Kullanıcının FCM token'ını kaydeder veya günceller
         * POST /users/fcm-token
         */
        public async saveFcmToken(params: SaveFcmTokenRequest): Promise<SaveFcmTokenResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/users/fcm-token`, JSON.stringify(params))
            return await resp.json() as SaveFcmTokenResponse
        }
    }
}

export namespace lib {
    /**
     * Type definitions
     */
    export interface Ingredient {
        name: string
        amount?: string
        unit?: string
    }

    export interface Instruction {
        step: number
        text: string
    }

    export interface Recipe {
        id: string
        title: string
        "image_url": string | null
        "created_at": string
        "created_user_id": string
        ingredients: Ingredient[] | null
        instructions: Instruction[] | null
    }

    export interface RecipeSummary {
        id: string
        title: string
        "image_url": string | null
        "created_at": string
    }

    export interface User {
        id: string
        "clerk_id": string
        "created_at": string
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "mini-apps-center-8u7i-Generated-TS-Client (Encore/v1.56.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
